### ISSUE TITLE
请问有支持朗读弹幕的计划吗

### ISSUE THREAD

**Issue by CaptainYukinoshitaHachiman** [pandaGao/bilibili-live-helper#1]

**Comment by pandaGao** [comment]
有的。
之前部分主播和我反映过语音播报弹幕在实际的使用体验上并不是很好，所以暂时降低了优先级。
具体的实现方式已经进行过一些了解，主要还是在考虑如何优化使用体验。
预计会在未来2~3个功能性更新版本内提供这个功能。
