### ISSUE TITLE
请问是否可以直接在 GitHub 提供下载版本？

### ISSUE THREAD

**Issue by emptymalei** [pandaGao/bilibili-live-helper#10]
作为北美用户，使用百度盘下载速度极慢，请问能否直接使用 GitHub 的 Release 功能来提供下载呢？

感谢 ❤️ 

-------

终于从百度盘下载下来了，用了一下发现这个简直是我用过的弹幕姬里面最棒的了！虽然好像不能再叫弹幕姬了，但是不管叫什么，真的很棒。:yum:

**Comment by pandaGao** [comment]
感谢支持 之前我上传Release一直不成功 后面发布新版本后我会再尝试下的 如果成功了的话 我也会在官网上加上Github的资源链接

**Comment by emptymalei** [comment]
十分感谢。On Oct 12, 2017 10:21 AM, Ryan Gao <notifications@github.com> wrote:感谢支持 之前我上传Release一直不成功 后面发布新版本后我会再尝试下的 如果成功了的话 我也会在官网上加上Github的资源链接
