### ISSUE TITLE
Connection Reset Error

### ISSUE THREAD

**Issue by dsh0416** [pandaGao/bilibili-live-helper#11]
The app continuously connecting to the server trying to get the latest danmuku status, but failed.
I've tried the latest version of this project including the latest commit on develop branch.
But the problem stills.
I tried to catch the packet from wireshark to find the reason.
It seems that the server closes the connection immediately when the client trying to establish the websocket connection.
It seems to be some problems since the latest update of bilibili made lots of modification in URLs.
I've exported a wireshark packet log in attachment for debugging.

弹幕姬持续地向 Bilibili 服务器发起获取弹幕的请求，但是持续失败无法连接。
我已尝试了最新版本的代码，包括 develop 分支上的最新 commit。而问题依旧。
我尝试使用 Wireshark 进行抓包来寻找问题原因。
看起来似乎 Bilibili 服务器在建立 WebSocket 连接时立刻中断了 TCP 连接。
这可能和近期 Bilibili 直播更新后大量 URL 地址的修改有关。
我已导出了一份 Wireshark 的抓包记录，供 Debug 使用。

[wireshark.zip](https://github.com/pandaGao/bilibili-live-helper/files/1438530/wireshark.zip)

**Comment by pandaGao** [comment]
Hi 今天出现的连接失败的问题是B站直播间改版了 我之前获取房间真实ID的方法失效了 我已经更换到新的API 马上就发布1.0.2版本了 真的非常感谢你的认真反馈！ 晚上我一直在准备发布新版本 没有把本地的commit push上来 我一般第一时间会在QQ群里反馈的 群号是552745835 欢迎来一起交流！
