### ISSUE TITLE
小小的建议x

### ISSUE THREAD

**Issue by TobiichiAmane** [pandaGao/bilibili-live-helper#13]
能否让设置窗口关闭的时候，不退出弹幕姬？还有，，可不可以不让弹幕姬显示在窗口列表里，这样看起来真的很碍眼x
顺便，在Linux下似乎并不需要--disable-gpu就可以正常执行（Linux Mint 18.2 Sonya）

**Comment by pandaGao** [comment]
Hi 感谢反馈
目前对于关闭窗口的处理为了让各个平台下相对统一就对设置窗口和工具栏窗口的关闭都做了同样的“退出”操作 这个我会考虑一下的
然后关于窗口这件事情 目前在Mac下是只会有一个图标的 但是Windows上就会有两个图标 (linux我忘了...) 这个应该是electron本身的一个平台差异 主要是由于弹幕的窗口是需要置顶显示的 而设置窗口并不需要
至于Linux下的参数是electron推荐的参数 为了能启用透明窗口的特性 这个对于不同的Linux也确实会有不同 好像在ubuntu下会需要disable-gpu这个参数
