### ISSUE TITLE
新功能请求:增加本地API

### ISSUE THREAD

**Issue by Fmajor** [pandaGao/bilibili-live-helper#15]
能否让程序在本地监听一个端口，并提供常用功能的api（比如发弹幕）供本地其他程序调用？
这样就不用我们自己再处理登陆之类的了。

**Comment by pandaGao** [comment]
Hi
我有计划在下个major版本中提供“插件系统” 可以支持运行用户自定义的js脚本 并将弹幕信息和部分api以依赖注入的形式提供给开发者使用

相比可控的插件环境 直接监听本地端口相对来说较为“危险” 大多数用户对这件事情并没有感知 但如果被利用 当用户打开了恶意软件时 就可以直接通过向本地的端口发送请求来进行恶意的发言等操作 （这样可能会让用户觉得弹幕库本身就是恶意软件）
而如果是插件 至少用户会有手动引入的过程 并且当插件需要使用登录态相关API时 我会让用户确认授权 这样更容易鉴别出恶意行为的来源
更加具体的实现方式我在逐步规划中 有更多的第三方开发者相关的需求也可以和我继续讨论
感谢反馈！
