### ISSUE TITLE
建议添加安装说明

### ISSUE THREAD

**Issue by zhangysh1995** [pandaGao/bilibili-live-helper#16]
表示没用过 js 的项目，完全不知道怎么安装，问过朋友才了解了。能不能加一个安装说明？

**Comment by pandaGao** [comment]
如果想要本地编译运行这个项目 请先安装最新版本的node以及npm
然后在项目文件夹下运行
`
# 安装依赖
npm install

# 启动开发环境
npm run dev
`
大部分node.js的项目都可以使用这两个命令启动开发环境
