### ISSUE TITLE
直播间状态一直为准备中

### ISSUE THREAD

**Issue by HyperSimon** [pandaGao/bilibili-live-helper#17]
<img width="1025" alt="2017-11-28 11 48 51" src="https://user-images.githubusercontent.com/9377192/33301704-362d4710-d432-11e7-82d8-b1bbe27fb7b5.png">
如图，是我漏了哪些步骤吗？

**Comment by pandaGao** [comment]
Hi
弹幕库只能获取直播间的状态 并不能直接开启直播 开启弹幕库只是连接上直播间的弹幕服务器 并获取房间弹幕
