### ISSUE TITLE
网易云点歌接口出错

### ISSUE THREAD

**Issue by Snrat** [pandaGao/bilibili-live-helper#19]
如题。

**Comment by zgq354** [comment]
刚刚给项目用到的 simple-netease-cloud-music 项目提交了 PR ，等作者合并了应该就可以了

**Comment by pandaGao** [comment]
@zgq354 Hello 我刚好也在看这个问题 刚刚看到你在那个项目提的pr! 非常感谢 等到作者发布新的版本后 我这边也会马上更新的!

**Comment by Snrat** [comment]
@zgq354 感谢你的PR，我今天也在关注这个问题

**Comment by pandaGao** [comment]
问题已修复 稍后会发布v1.1.1版本
