### ISSUE TITLE
在直播间有短号的情况下只支持短号，不支持原房间号

### ISSUE THREAD

**Issue by Genteure** [pandaGao/bilibili-live-helper#2]
用原房间号试了半天。。

**Comment by pandaGao** [comment]
最近Bilibili修改了一些访问规则 目前拥有短位房间号的房间在使用真实房间号访问时会301到短位房间号的URL 之前的弹幕姬为了保证能够兼容短位和真实房间号每次都会抓取页面获取一下真实房间号 才会导致目前的情况 后面的版本会修复这个问题

**Comment by Genteure** [comment]
一直是跳转的吧，这个策略我记得不是最近修改的吧

**Comment by pandaGao** [comment]
我记得最早的时候 我还是能访问到真实ID的URL的 后来就都会跳转了 也可能是和具体的房间有关 后续我会在bilibili-live那个项目中把这个问题修复的
