### ISSUE TITLE
礼物中奖统计相关问题

### ISSUE THREAD

**Issue by Snrat** [pandaGao/bilibili-live-helper#22]
开启中奖统计后，一旦切换左侧的菜单，原来的统计就会消失。
希望能够记住统计，即便在关闭弹幕库之后也能依旧保存，转为txt等格式文件进行保存，而不是一次性，随时可能由于误操作而清空的这种。

**Comment by pandaGao** [comment]
目前会对中奖名单在开启弹幕库的期间进行保存 因为实现上的一点问题目前抽奖统计还是需要保持在抽奖页面才行 后续大版本更新后会解决这个问题
