### ISSUE TITLE
目前版本1.1.2 语音播报貌似不能用了

### ISSUE THREAD

**Issue by wallena3** [pandaGao/bilibili-live-helper#25]
声音的选择没有   打开之后没有语音播报

非常感谢提供的linux版本，很需要，谢谢
![_ _20180121205854](https://user-images.githubusercontent.com/11361768/35194390-e8027f74-feed-11e7-9071-638c18136df6.png)

**Comment by pandaGao** [comment]
Hello 感谢支持与反馈 语音播报的功能需要系统本身的语音合成模块的支持 我本人使用的是Mac Mac自带了多种语音合成模块 弹幕库也能较好的识别系统的语音合成模块 Window下需要通过文本到语音设置来选定默认使用的模块 而Linux由于版本较多 我使用过Ubuntu进行过测试 默认情况下确实没有语音合成相关的模块 后续为了方便没有语音合成模块的系统 我可能会引入在线语音合成服务来解决这个问题

**Comment by wallena3** [comment]
好的  这个也不是什么重大的bug 不着急哈  有这个系统通知其实全屏下就够用了，再次感谢
