### ISSUE TITLE
在 AUR 上打了个包

### ISSUE THREAD

**Issue by OriginCode** [pandaGao/bilibili-live-helper#27]
这样 Arch Linux 用户会更方便的吧
顺便更改了主程序的名字以方便使用
地址：https://aur.archlinux.org/packages/bilibili-live-helper

**Comment by pandaGao** [comment]
Hello
感谢支持！
我还没使用过Arch 对AUR的包管理机制也不太了解 大概看了一下你发布的安装脚本好像是从 [这里](https://github.com/OriginCode/AURFiles)把文件下载下来然后解压缩 
所以如果后面弹幕库更新了是不是还需要你手动的升级AUR包的版本并上传压缩包

**Comment by OriginCode** [comment]
@pandaGao 是的，我需要更新我仓库中的那个压缩包

**Comment by OriginCode** [comment]
另外刚刚打了一个 git 版的，从这个仓库获取，本地编译
晚些时候传到 AUR 上

**Comment by pandaGao** [comment]
Thanks Linux系统情况比较复杂 目前我还没有针对不同平台打包的计划 可能后面也只会提供压缩包  不过多一种选择也是一件好事 再次感谢 ：）

**Comment by OriginCode** [comment]
@pandaGao Umm，之所以不用这个仓库的release是因为没有最新的1.1.2版本
如果加上1.1.2版本的话就不用我自己的仓库啦
