### ISSUE TITLE
linux下没有语音播报的语音

### ISSUE THREAD

**Issue by AoEiuV020** [pandaGao/bilibili-live-helper#29]
另外右边一条弹幕框不能半透明，
系统是linuxmint18,

**Comment by pandaGao** [comment]
Hello
大部分Linux系统好像确实没有语音合成的模块提供 由于我是直接使用的系统提供的语音合成功能 所以在Linux下语音播报应该是无法使用的
然后关于窗口透明化的问题 有在启动的时候添加README中的参数吗

**Comment by OriginCode** [comment]
@pandaGao 語音播報在 Linux 中應該可以通過安裝一些包來提供

**Comment by nicholascw** [comment]
考虑一下支持ekho/espeak嘛?
