### ISSUE TITLE
Download网站DNS解析丢失

### ISSUE THREAD

**Issue by devilcn** [pandaGao/bilibili-live-helper#30]
http://bilibili.danmaku.live/ 该网站已无法解析，烦请修复DNS解析，十分感谢！~

**Comment by pandaGao** [comment]
Hello
因为是从国内购买的域名 目前需要通过一些认证 我正在和域名供应商沟通 会尽快解决DNS的问题

**Comment by devilcn** [comment]
现在已经恢复了，辛苦了！另外readme.md里面写最新版本是1.1.1，我用你的源代自己编译也是1.1.1~

**Comment by pandaGao** [comment]
1.1.2版本的代码目前在develop分支

**Comment by devilcn** [comment]
收到！感谢回答。祝元宵节快乐！
