### ISSUE TITLE
能否解決在Linux下的窗口前置問題

### ISSUE THREAD

**Issue by OriginCode** [pandaGao/bilibili-live-helper#32]
我的一位朋友用了以後，發現切換工作區（Workspace）時彈幕窗口不能在每一個工作區保持，他使用的是GNOME桌面環境。
另外在我的KDE桌面環境上，不能直接前置彈幕窗口，必須先打開防誤觸模式然後再關閉才能前置，請問這是Feature還是Bug。:smile:

**Comment by pandaGao** [comment]
workspace的事情我还不太清楚 关于置顶这个问题 因为在切换防误触模式的时候我会重新设置工具栏和弹幕视图是否置顶(虽然在创建窗口时已经指定了总是置顶) 根据你说的情况 很可能在部分Linux上创建窗口时的alwaysOnTop设置并没有生效 但创建窗口后再调用setAlwaysOnTop设置置顶是有效的
感觉可以在[此处](https://github.com/pandaGao/bilibili-live-helper/blob/ca5322666d4ebd1cb639b07f2c3df6ff1d021fab/app/src/main/index.js#L120)
添加一句`danmakuWindow.setAlwaysOnTop(true)`来解决

**Comment by OriginCode** [comment]
@pandaGao 我在[此處](https://github.com/pandaGao/bilibili-live-helper/blob/ca5322666d4ebd1cb639b07f2c3df6ff1d021fab/app/src/main/index.js#L120)加上了
```
toolbarWindow.setAlwaysOnTop(true)
danmakuWindow.setAlwaysOnTop(true)
```
解決了問題！
