### ISSUE TITLE
問一個很蠢的問題...

### ISSUE THREAD

**Issue by kinia3020** [pandaGao/bilibili-live-helper#33]
請問下載了壓縮檔，解壓縮之後要怎麼用..?＞＜

**Comment by pandaGao** [comment]
看你是什么系统了 Windows的话 直接双击执行.exe文件就可以 Mac拖到Application文件夹里面 Linux的话 需要在命令行启动 并且加上 --enable-transparent-visuals --disable-gpu参数

**Comment by kinia3020** [comment]
我是mac的但是解壓縮之後，是一個資料夾，不是dmg檔，所以不太知道哪一個才是app本體..

**Comment by pandaGao** [comment]
也有可能是你下错了压缩包 请注意下载文件名中带mac的压缩包 解压出来应该就是一个app包 直接拖进Application文件夹就可以了 https://pan.baidu.com/s/1mjhUfsW

**Comment by kinia3020** [comment]
ＱＡＱ這個網盤連結和官網的連接都是已失效..

**Comment by pandaGao** [comment]
emmm 我这边看还是有效的 或者你可以加qq群552745835 在群文件里也有下载 再或者你可以给我发一封email me@pandagao.com 我会把最新版本的弹幕库发给你

**Comment by kinia3020** [comment]
啊..想起來了可能是因為我在國外，所以被限ip了＞＜

**Comment by kinia3020** [comment]
非常不好意思麻煩了，終於弄好了＞＜
