### ISSUE TITLE
原先的那种设置方式可以提供可选设置吗

### ISSUE THREAD

**Issue by limitLiu** [pandaGao/bilibili-live-helper#4]
开个主窗口感觉交关不适意

**Comment by pandaGao** [comment]
在实现上主窗口才是真正的数据源 如果在弹幕窗口中同步一份设置会产生很多同步的问题 目前弹幕视图只是一个纯展示的窗口 接受来自弹幕池的消息并渲染弹幕 我拆分出多个窗口主要就是为了区分开设置和展示两个不同部分的功能

**Comment by limitLiu** [comment]
原生的我写过是可以隐藏窗口的 理论上 Electron 应该也提供了此类操作 所以可否提供一个此类设置 多承多谢哉😂 个么侬实在没有时间的话 我 fork 一份自己改一下 // 看你的协议是 MIT 的

**Comment by pandaGao** [comment]
隐藏窗口是可以的 我也提供了最小化窗口的按钮 如果还有其他需要欢迎fork 不过我最近在修改一些比较底层的库和事件 建议等到1.0.1版本正式更新后再fork吧
