### ISSUE TITLE
[建议]点歌板 - 输出文件

### ISSUE THREAD

**Issue by devilcn** [pandaGao/bilibili-live-helper#40]
感谢作者开源！
在测试使用的过程中发现点歌板中输出`current_music_list.txt`和`finished_music_list.txt`两文件中超过16字符后的内容不会显示，能否增长输出字段长度以便OBS完整抓取显示？
另外这两个文件中均不包含点歌人ID，能否在增加长度后添加点歌人ID呢？多谢！

**Comment by StringKe** [comment]
播放列表建议可以配置详细输出的设置 如关键词{title} - {user} - {song_is}这种变量类型可以随用户自己定义
