### ISSUE TITLE
[反馈] 建设性意见等

### ISSUE THREAD

**Issue by StringKe** [pandaGao/bilibili-live-helper#42]
1. 点歌板歌曲信息文件的输出
2.在pubg等游戏全屏时候无法显示置顶 必须是全屏无窗口模式才可以看到
3.礼物和用户弹幕分屏功能？
4.弹幕发送设置那里的文本输入框右下角的拉取会导致滚动条出现

**Comment by Snrat** [comment]
1.请查看软件内说明
2.无解
3.作者暂无此计划
4.不能算Bug吧

**Comment by StringKe** [comment]
1.文件输出的信息过于简单了

建设性意见没说是bug

**Comment by shugen002** [comment]
关于2，
全屏模式下消失，是因为游戏会直接操作显卡，显示的画面不经过系统处理，而全屏窗口模式下，游戏画面会输出到系统，在输回显卡输出到显示器，此时，系统就可以把弹幕库的界面画上去，你也应该留意到在窗口全屏模式下的帧率降低，也是这样的原因。
个人建议：两个显示器。。。
