### ISSUE TITLE
实时关注提醒和，关注人数貌似并没有生效

### ISSUE THREAD

**Issue by yanjingenious** [pandaGao/bilibili-live-helper#5]
![qq 20170830140126](https://user-images.githubusercontent.com/19990773/29857548-cbcc5754-8d8b-11e7-9ed4-3ed508f6e32f.png)

**Comment by yanjingenious** [comment]
希望能添加歌词信息的显示功能，读弹幕功能建议参考下小葫芦弹幕助手，现在这个读弹幕连名字都读，感觉怪异无比

**Comment by yanjingenious** [comment]
1.那个发送弹幕功能，可以和上面的弹幕列表合并，应为开了防误触功能，就没办法发弹幕了，有时候修仙不能说话，又在窗口全屏模式这就尴尬了。
2.希望直接能在点歌列表添加歌曲，还有就是能添加一个空闲播放列表，最好是能导入网易云的歌单，这样就比较完美没人点歌，就播放歌单里的，有点歌就播放点歌的。

**Comment by pandaGao** [comment]
关注的功能已经在1.0.1版本修复了 马上就可以更新了 防误触模式下就是为了避免在游戏中鼠标误触弹幕姬视窗所以屏蔽了鼠标事件 然后点歌空闲列表的事情我有这个计划了 具体实现还要考量一下

**Comment by yanjingenious** [comment]
@现在最需要的功能应该是显示歌名这个功能了，现在没办法显示在直播姬里

**Comment by yanjingenious** [comment]
@pandaGao 现在最需要的应该是显示歌名的功能了

**Comment by pandaGao** [comment]
@yanjingenious 目前我还在寻找一个合理的方式向OBS等推流软件输出可展示的控件 我比较倾向于使用Browser Resource为推流软件提供可捕捉的来源 不过那样做的话工作量还是比较大的 所以还在考虑中
