### ISSUE TITLE
建议更改项目名称

### ISSUE THREAD

**Issue by MittWillson** [pandaGao/bilibili-live-helper#7]
由于和现存项目 "[弹幕姬](https://www.danmuji.cn/)" 冲突
导致近期很多在弹幕姬群询问 "新弹幕姬" 信息的人剧增
在此诚挚建议作者更换项目名称以避免小白用户混乱,  且尽量避免与"弹幕姬"关联
另: 弹幕姬项目还在维护中

**Comment by pandaGao** [comment]
@MittWillson 我会在下个minor version的更新中更改应用的命名  我也在想一个好玩一点的名字 不过大体上也是围绕在bilibili、直播、弹幕等关键词的组织上 目前我比较倾向于叫“弹幕库” 取自danmaku的谐音 总之我可以避开“弹幕姬”这个强关键词 因为这个项目目前只有我一个人在空闲时间才能维护 在推广上也没有下太多功夫 就像我在其他地方说过的 原本我是为了在mac上做出能够辅助看弹幕的应用才有了这个项目 当时也已经有直播姬了 之前我一直认为弹幕姬是一个比较官方的叫法 类似于这类软件的一种代称 所以也在项目中使用了弹幕姬这个词 再加上其实这个项目本身也是开源的 我主要希望借助这个项目来熟悉electron 对我来讲“好玩”才是第一位的 目前使用我这个项目的用户数已经超出我的预期了 其实我也没有想到会对之前的弹幕姬项目有这么大的影响 如果因为命名的问题造成了很多困扰 我觉得没有必要 我会避开弹幕姬这个名字 我还是希望能让两个项目都能更好地发展 目前我会让这个issue保持open 等待后续跟进

**Comment by pandaGao** [comment]
@MittWillson  Hello 久等了 最近由于B站直播间改版 我之前的版本出现了无法连接的问题 所以今天紧急修复了一下 感觉时间也挺久的了 就不等到下个minor version再更名了 从v1.0.2起 这个项目就正式更名成Bilibili直播弹幕库了 这个issue也终于可以close啦！
