### ISSUE TITLE
macOS运行后卡在loading界面

### ISSUE THREAD

**Issue by lightumcc** [pandaGao/bilibili-live-helper#79]
macOS运行后卡在loading界面，
![image](https://user-images.githubusercontent.com/60721270/137588655-4889f985-b600-4e37-9311-94fe76361795.png)

**Comment by ColaMint** [comment]
我也是

**Comment by a152917** [comment]
有木有解决方案啊，大佬们

**Comment by afawoele** [comment]
我也是
