### ISSUE TITLE
那个～有没有考虑把礼物感谢功能加进去呢

### ISSUE THREAD

**Issue by a741424975game** [pandaGao/bilibili-live-helper#8]

**Comment by pandaGao** [comment]
Hi 礼物答谢功能在逻辑上其实不算很复杂 只是有很强的个性化设置的需求 我个人认为实现一个很易用高自由度的答谢功能其实还是比较复杂的 我有这个计划 不过在我这里优先级不是很高 主要因为这个功能好像已经有相关的比较好的实现了
