### ISSUE TITLE
[功能建议] 直播间 ID 为空时，开启弹幕姬默认使用已登录账号的直播间 ID

### ISSUE THREAD

**Issue by ApolloZhu** [pandaGao/bilibili-live-helper#9]
无直播间 ID 且未登录则保持目前逻辑

**Comment by pandaGao** [comment]
Hello 之前没有这个功能是因为我只能获取到主播的房间原始ID 而许多主播是有短位ID的 目前如果使用原始ID进入一个有短位ID的房间 弹幕姬不能正常运行 并且每次输入的房间号会自动保存 也存在有登录后不打开自己的直播间的情况 所以暂不考虑这个功能
